### ISSUE TITLE
[SP service Records] Check why just showing 5 records in the Portal

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/tng-portal#234]
Reported environment was pre-int in 
https://pre-int-sp-ath.5gtango.eu/service-management/network-service-instances

There is a problem with the records display. There are more than the ones displayed in the list.

![image](https://user-images.githubusercontent.com/11843/46016640-3aac5000-c0cd-11e8-8bd6-b323ee03bd20.png)

**Comment by anapolg** [comment]
Not able to reproduce .
