### ISSUE TITLE
[SP Slice manager] Wrong json reception when no sla is selected

### ISSUE THREAD

**Issue by alemanyp** [sonata-nfv/tng-portal#235]
There's aproblem about how the portal sends the sla value when no uuid is selected. please see the differences below:

Json coming from protal/GK --> None goes without ' '
{'author': 'Pol', 'name': 'NST_test_10', 'version': '1.0', 'vendor': 'CttC', 'sliceServices': [{'nsdID': '4c7d854f-a0a1-451a-b31d-8447b4fd4fbc', 'servname': 'ns-squid-haproxy', 'slaID': None}]}

Json coming from slice_cli --> 'None? goes WITH ''
{'author': '5gtango', 'name': 'Test_10', 'version': '1.0', 'vendor': '5gTango', 'sliceServices': [{'nsdID': '4c7d854f-a0a1-451a-b31d-8447b4fd4fbc', 'servname': 'ns-squid-haproxy', 'slaID': 'None'}]}

**Comment by anapolg** [comment]
@alemanyp which one is the desired behaviour?

**Comment by alemanyp** [comment]
Json coming from slice_cli --> 'None' goes WITH ' '
{'author': '5gtango', 'name': 'Test_10', 'version': '1.0', 'vendor': '5gTango', 'sliceServices': [{'nsdID': '4c7d854f-a0a1-451a-b31d-8447b4fd4fbc', 'servname': 'ns-squid-haproxy', 'slaID': 'None'}]}

**Comment by anapolg** [comment]
@alemanyp ok. I'll change it as soon as possible.

**Comment by anapolg** [comment]
Together with #263
