### ISSUE TITLE
[User Register] Terms of usage of the Portal

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-portal#237]
During register, the user must acept terms of usage in order to be able to continue.

Checkbox with some text like this:
"By checking this I confirm that I’ve read and agreed with our <link>Terms of usage</link>"

The link to this terms of usage:
(@jbonnet will provide it)

**Comment by jbonnet** [comment]
@anapolg My suggestion for the Terms of usage (open to changes, of course):

1. Collection of Personal Information

5GTANGO collects and uses your personal information to operate SONATA V&V and Service platforms and for a better user experience. Your personal information is requested when you register with our Portal/API to access restricted content. Your Portal navigation/API usage may also be monitored for statistical purposes. 5GTANGO takes responsibility for protecting the privacy and data of all users. Personal data is not shared with third parties.

2. Use of your Personal Information

When you register or submit your personal information in any 5GTANGO Portal/API, we do not share that information with third parties without your permission. It is only used for the purposes stated above.

3. Security of your Personal Information

5GTANGO uses a variety of security technologies and procedures to help protect your personal information from unauthorized access, use, or disclosure. 5GTANGO secures the personally identifiable information you provide on computer servers in a controlled, secure environment protected from unauthorized access, use, or disclosure.

4. Data Retention

5GTANGO will retain your information for as long as your account is active or as needed to provide you services. If you wish to change your personal information or request that we no longer use it, please contact us.

**Comment by jbonnet** [comment]
whatever the designer decides is fine for me...
