### ISSUE TITLE
[SDK integration] Create mockups in Invision for the SDK integration in Portal

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-portal#243]
Related to [tng-sdk-project #54](https://github.com/sonata-nfv/tng-sdk-project/issues/54)

**Comment by StefanUPB** [comment]
I created a wiki page with the mockups and required interactions with the REST API of the SDK services here: https://github.com/sonata-nfv/tng-portal/wiki/UPD-workflow-mockups

It still contains a number of todos that also affect the SDK side (e.g., missing REST endpoints or required fields in a response).

**Comment by anapolg** [comment]
Related to user story [#456](https://git.cs.upb.de/5gtango/UserStories/issues/456)

**Comment by stefanbschneider** [comment]
Regarding the 2. point: I just [merged some updates](https://github.com/sonata-nfv/tng-sdk-project/pull/66) with some adjustments to the REST API and mostly to improve their documentation through the Swagger spec. Now, the first view (descriptor generation) should be ready regarding the APIs.

I updated the [wiki page](https://github.com/sonata-nfv/tng-portal/wiki/UPD-workflow-mockups) accordingly.

**Comment by stefanbschneider** [comment]
@anapolg Can we close this issue? I don't think we need extra mockups.

**Comment by anapolg** [comment]
Actually we need in order to respect the styles of the rest of the app :) Designer already talked to me and she's doing them with deadline end of march if I remember correctly.

**Comment by stefanbschneider** [comment]
Ah ok, so we'll use the designed elements directly for buttons etc in the GUI?

**Comment by anapolg** [comment]
You'll base your developments on what's specified by the designer, yes. Button placements, number of screens required, input placements, colors, menus and so on.

**Comment by anapolg** [comment]
We already have all the designs. I'll share them as I create the issues with the description of what's required to do. Thanks a lot @stefanbschneider for your first mockups. They were very helpful.
