### ISSUE TITLE
[SP Slice template creation] Add NetSlice QoS

### ISSUE THREAD

**Issue by alemanyp** [sonata-nfv/tng-portal#247]
Here I leave the new fields to add into the NST frontEnd.

Thanks Ana!

![imagen](https://user-images.githubusercontent.com/30235199/50841670-807fe200-1365-11e9-94a8-dcf04a3f06bb.png)

**Comment by alemanyp** [comment]
Updated Issue, it has been simplified

![imagen](https://user-images.githubusercontent.com/30235199/51177043-dd781c80-18be-11e9-8b4d-836cbb41b509.png)

**Comment by anapolg** [comment]
This idea is in PAUSE until @alemanyp says the opposite.

**Comment by anapolg** [comment]
I guess this is no longer needed, right @alemanyp ? Please can you close the issue if you agree?

**Comment by alemanyp** [comment]
You are right @anapolg, closing the issue.
