### ISSUE TITLE
Change ingress points offered during instantiation

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-portal#252]
Ingresses must be:
bcn-1
bcn-2
bcn-3
bcn-4
They all must allow the introduction of an IP as an string that will be sent in the request of the ns instantiation.
(cc @juanlucruz )

**Comment by jbonnet** [comment]
@anapolg Are these ingresses hardcoded on the Portal's side, or should there be an API fetching them?

**Comment by anapolg** [comment]
Right now they are hardcoded. The conclusion was they will remain hardcoded until we develop an API to fetch them but for now, hardcoded are just fine to continue with everybody's developments.

**Comment by anapolg** [comment]
At the moment: [ 'Athens', 'Aveiro', 'Barcelona', 'Paderborn' ]. Changing this to the required ones.

**Comment by anapolg** [comment]
Now the request to instantiate includes:
ingresses: [{location: "bcn-1", nap: "1.1.1.1"}]
