### ISSUE TITLE
[SDK] Show generated descriptors

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-portal#269]
As soon as you've got the number of VNFs and the general information form is completed (all the first step is completed correctly) you need to send a request to generate the skeleton of the descriptors to the SDK (tng-sdk-project). The information retrieved will be included in the _description_ boxes displayed in the second step for NSD and VNFDs.

**Comment by stefanbschneider** [comment]
Once the `tng-sdk-project` REST API exposes the generated files, it should be easy to display them (read-only) in the portal. Depends on this: https://github.com/sonata-nfv/tng-sdk-project/issues/83

**Comment by stefanbschneider** [comment]
Display descriptors inside frontend: https://stackoverflow.com/a/57292853/2745116

**Comment by anapolg** [comment]
Please check https://pre-int-sp-ath.5gtango.eu/service-management/network-services/network-service-instances/ea97e082-a304-4dab-b750-b69d05f4c441
Try to open one of the table entries in the bottom of the page. If what you want is something similar you can try to reuse some of the code from that component.

**Comment by stefanbschneider** [comment]
Thanks. This looks to me like tables right? My plan was to directly display the whole content of the descriptors. Do you have anything implemented for displaying text files (eg, descriptors) already?

But I'm putting this on hold for now and focusing on the next issue #273

**Comment by anapolg** [comment]
Yes, that one is a table and if you click any entry it gets opened while displaying more info.

For just displaying texts I have this usually:
![image](https://user-images.githubusercontent.com/35800470/62268970-ddda9e00-b431-11e9-85f2-05d7ed62e683.png)
https://pre-int-sp-ath.5gtango.eu/settings/vim/88888888-2222-3333-4444-888888888888

Styles of that box are general to all the app under the class name "description". If you search in that component (or you search the string ' class="description" ') you will find a couple examples on how to use it.

If you just want to display text, use a simpler example of the description boxes, like the one below. The previous includes logic to display JSON or text (editable JSON) in case you want to modify the JSON variable displayed. This one below just displays a text coming from a variable. No edition no nothing extra.

![image](https://user-images.githubusercontent.com/35800470/62269196-8983ee00-b432-11e9-9a6e-d6acff7b59f9.png)
https://pre-int-sp-ath.5gtango.eu/service-management/network-services/services/6a21d937-97af-4cdc-9678-e7ca511e10e2

**Comment by stefanbschneider** [comment]
Nice, thanks! I'll have a look. I don't need editing. Some kind of syntax highlighting would be nice, but not mandatory.

Also, I just remembered, I previously used [Google prettify](https://github.com/google/code-prettify) to show generated descriptors in my old, pure [JS descriptor generator](https://github.com/sonata-nfv/tng-sdk-descriptorgen/blob/10c6c9cfffafa85f24d52ba09d3acdc4c0bbebb3/generate.js#L243).

I'll just check the option and go with the one that looks best and is easiest :)
