### ISSUE TITLE
[SP VIM config] Converter YAML to JSON

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-portal#270]
Is there a converter from pasted YAML to JSON object?

**Comment by jbonnet** [comment]
Check [here](https://gist.github.com/otobrglez/66274639697f377de8ec8047a248b8f0)

**Comment by anapolg** [comment]
Sure @jbonnet but I need one for Angular to transform the pasted VIM config in YAML to a JSON. Maybe there's an npm module doing the same. I'll do the search later when I finish with other urgent issues :)

**Comment by anapolg** [comment]
Please @felipevicens check if the behavior is fine for you. If any problem reopen the issue.
