### ISSUE TITLE
[SDK] Create package description page

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-portal#271]
The page must include:
- Title and "Service name" input on the top left
- "CANCEL" button on the top right
- A form titled "Description" with author and vendor inputs
- A description text box (styles already defined for this at app level, you can search examples all over the app)
- A numeric input allowing at most two digits.
- A circle next to the title "Description" that will be empty (white) while the form is empty and grey (there is a color constants file including the colors of the app) when ready. If error it becomes red (again, there is a color constants file). 

Attached picture of the final result:
![createSDKPackage_1](https://user-images.githubusercontent.com/35800470/55078494-95356180-509a-11e9-97d3-3e7fb2a1e431.png)

**Comment by stefanbschneider** [comment]
@zulfiqarjunejo This is implemented now right? Can we close the issue?

**Comment by stefanbschneider** [comment]
@anapolg @zulfiqarjunejo Where is/should be the code for the SDK portal? In the `master` branch or the [`sdk` branch](https://github.com/sonata-nfv/tng-portal/tree/sdk)?

**Comment by anapolg** [comment]
@stefanbschneider For the moment let's keep it in the SDK branch until it is finished. 

It is not going to be deployed in any environment for the moment and in case of error it won't affect the deployed versions in pre-int nor in int.

**Comment by stefanbschneider** [comment]
That makes sens 👍  @zulfiqarjunejo should probably still fetch the newest version from `master` every now and then and merge it into the `sdk` branch to make sure we're always working on the newest version and that we can merge it easily in the end when it's done.
