### ISSUE TITLE
[SP Slice] Update slice instantiation to include ns-slas list

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-portal#274]
Include the list of network services with their related slas (if existing) and enable the update of the chosen sla.

Two steps pop up with this list and then the form with the name and description.

**Comment by anapolg** [comment]
Example of the body of the request:
```
{
  nst_id: this.data.nstId,
  name: this.instantiationForm.get('nsiName').value,
  description: this.instantiationForm.get('nsiDescription').value,
  'request_type': 'CREATE_SLICE',
  services_sla: [
    {
      service_uuid: uuid,
      sla_name: name,
      sla_uuid
    }
  ]
}
```

**Comment by anapolg** [comment]
@jbonnet hi. We (@alemanyp and me) need some support from you in this issue. We are sending the body above to instantiate an slice at this moment. The reason is the inclusion of the SLA concept in the Slices, like it happens with the NS instantiation. Is the GTK prepared to receive that kind of body structure?

**Comment by jbonnet** [comment]
@anapolg @alemanyp To which endpoint is this body being sent to?

**Comment by jbonnet** [comment]
Forget it, `/requests`...

**Comment by anapolg** [comment]
Yes, a POST to http://pre-int-sp-ath.5gtango.eu:32002/api/v3/requests in this case

**Comment by jbonnet** [comment]
@anapolg @alemanyp Nop, sorry, at the moment the GTK is not taking into account this `services_sla` parameter... You have it as an array, can there be multiple SLAs?

**Comment by alemanyp** [comment]
Yes, each service might have its won SLA.

**Comment by jbonnet** [comment]
Ok, it has to be [added](https://github.com/sonata-nfv/tng-gtk-sp/issues/412); when do you need this?

**Comment by anapolg** [comment]
I have it already implemented and @alemanyp too as far as I know so.. whenever you can? My changes are not merged yet so no hurry on my side nor on the Portal users' side

**Comment by alemanyp** [comment]
not now, but maybe tomorrow we can work on it If it fits in your schedule. If not next, week. It shouldn't take too much to integrate a new parameter into an already working json.

**Comment by jbonnet** [comment]
Ok, I'll try to implement it first thing tomorrow...
