### ISSUE TITLE
[SDK] Automate deployment of SDK backend and frontend

### ISSUE THREAD

**Issue by stefanbschneider** [sonata-nfv/tng-portal#278]
After creating the descriptor generation page in Angular #269, you should integrate the frontend with the `tng-sdk-project` running in the backend.

You should pull the Docker image from Docker Hub with `docker pull sonatanfv/tng-sdk-project` and test the REST API as described in the Readme: https://github.com/sonata-nfv/tng-sdk-project#service-mode-with-rest-api

For this you'll need Docker installed on your development machine. Follow the steps here to install and configure it correctly on Ubuntu:

* https://docs.docker.com/install/linux/docker-ce/ubuntu/ (Just do the "Install using the repository" part)
* https://docs.docker.com/install/linux/linux-postinstall/ (Just do the "Manage Docker as a non-root user" part)

Then run the container locally on `localhost` and add the correct REST calls in the frontend to provide the descriptor generation functionality.

See mockups and description for relevant REST endpoints: https://github.com/sonata-nfv/tng-portal/wiki/UPD-workflow-mockups

**Comment by anapolg** [comment]
Testing of the API can be easily done with Postman

**Comment by anapolg** [comment]
> Then run the container locally on localhost and add the correct REST calls in the frontend to provide the descriptor generation functionality.

He will not be able to do all the API requests needed in this issue. In that case this issue will be in progress for weeks while he implements front end (which will take a while). Let's say this is for configuring the environment and just for that. Every time he needs to implement a call to backend another issue will be written so that he exactly knows what to do in every moment without the need to check all the time.

**Comment by stefanbschneider** [comment]
Ok, sounds good to me. So with configuring the environment you mean installing Docker, pulling the `sonatanfv/tng-sdk-project` image and testing if it works (if he can make REST calls with `curl` at all)?

Btw, this is just the first Docker image that will be needed. We'll also need the `tng-sdk-package` and later also the images of all other SDK tools that we want to integrate (e.g., validaiton).

**Comment by anapolg** [comment]
Actually, by configuring the environment I would say creating the automation of the environment. And by this I mean, automate the process to pull the images (all the ones required, including Portal) and run them. Like this any time he would need to update the environment to test or continue developing it would be quicker. What do you think?

**Comment by stefanbschneider** [comment]
Yes makes sense. So specifically, this would mean creating a `docker-compose.yml` that specifies which container images to pull and with which configurations to start them, right? Then he can simply start all services with `docker-compose up` (`--build` to rebuild changes in the frontend).

The Docker compose file should include (for now):

* The Angular frontend 
* `sonatanfv/tng-sdk-project`
* `sonatanfv/tng-sdk-package`
