### ISSUE TITLE
[SM Instances] Change runtime policies in NS running time

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-portal#282]
Instances can change their policies in running time so there is need for a select input to choose among the policies related to that NS.

**Update:** Policy manager has implemented the relative APIs to enable/disable a runtime policy
```
/policies/deactivate/{nsr_id}
/policies/activate/{nsr_id}/{policy_uuid}
```

"To avoid contradictory measures by the Policy Manager when an on-demand scaling is issued, that most likely will revert the scaling action, the NS policies will be able to be disabled (and enabled) in a particular NS instance. In the Portal this should be done going to the NS running instance listing and setting a button to disable (and enable to go back to policy). **AP: The Policy Manager should create an API to disable/enable the policy on a particular NS instance.**"
Coming from: https://git.cs.upb.de/5gtango/generalInfo/wikis/tango-wp5-2019-04-02

**Comment by anapolg** [comment]
cc @felipevicens

**Comment by jbonnet** [comment]
@anapolg You mean... in the Portal? Does the GK need to know this/build something?

**Comment by anapolg** [comment]
No, I don't think so @jbonnet. I will just address to /policies endpoint and that will point me to the policy manager component where the .../deactivate or .../activate will be. Please correct me if I am wrong @efotopoulou

**Comment by efotopoulou** [comment]
@anapolg  you are correct! policy manager given the nsr_uuid returns whether exists any policy to be activated or deactivated while the service is operative. The changes have been committed and wiki updated with the new API (@jbonnet swagger is pending to be updated also :-) )
