### ISSUE TITLE
[SP SLAs violations] Update the list and the detailed view to display new SLA model

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-portal#301]
Update the view to new SLA model including all the new fields added recently.

@ekapassa is there any Grafana graph including any information relative to SLA violations that I can use like there are some graphs in [here](http://pre-int-sp-ath.5gtango.eu:3000/d/SP_dash1/sp?orgId=1) relative to other monitoring issues.

**Comment by ekapassa** [comment]
@anapolg No unfortunately there aren't any graphs. But I have already created the apis that provide some information as discussed in the Paris meeting. But this  should be in the dashboard i think... Do you want them to provide you those apis?? But in that case the portal should generate the graphs.

**Comment by anapolg** [comment]
The APIs for this information are these: https://github.com/sonata-nfv/tng-sla-mgmt/wiki/API-Specification-master#sla-violations ? I'm thinking on including this information both in dashboard and sla violations page but not sure yet how it fits. We'll see.

**Comment by ekapassa** [comment]
From the page ypu mentioned the following:

1. https://github.com/sonata-nfv/tng-sla-mgmt/wiki/API-Specification-master#sla-violations --> the last one

1. https://github.com/sonata-nfv/tng-sla-mgmt/wiki/API-Specification-master#licensing --> the last three
