### ISSUE TITLE
[SM license] Create license list page

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-portal#307]
Create a page to list licenses showing this information in the table columns: ...
Rest endpoint: http://pre-int-sp-ath.5gtango.eu:32002/api/v3/slas/licenses

Note 1: [http://.../api/v3/slas/licenses](https://github.com/sonata-nfv/tng-api-gtw/blob/master/tng-router/config/sp_routes.yml#L144) not working @jbonnet @ekapassa 
Note 2: I need to implement licensing pages of Portal to complete SLA checks while instantiating a service (related to #306 -> which needs license buying page if license is private). We will need:
- licenses list
- a button to buy 

and what else? 
- License detailed page? 
- Are there user licenses and service licenses like in SONATA? In that case, do we want two separate submenus of licenses?

**Comment by ekapassa** [comment]
Hello Ana,
based on what we have on the licenses I propose the following:
1) lets make a detailed page with more info than the general list. In the detailed view we can show a) all the info we show in the general list b) in which NS is appied the license c) in with sla is applied d) in which customer is applied. Also from this detailed page we can add a link to the corresponding sla
2) the license general list is ok based on the inage you sent me in skype. (in will fix the date formats)

**Comment by ekapassa** [comment]
Also, @anapolg right now SLAM dont support an API for getting info for a specific license. would this be needed? or the /license endpoint is enough an you can parse each time the array item??

**Comment by anapolg** [comment]
Hi @ekapassa , preferably I would ask for an endpoint to get individual data of the license. If it is difficult for you to do so in these weeks I can manage with the actual endpoint.

**Comment by ekapassa** [comment]
I can provide the endpoint. But definitely not today.. :/ would be OK for you early next week?!?

**Comment by ekapassa** [comment]
I can provide the endpoint. But definitely not today.. :/ would be OK for you early next week?!?

**Comment by anapolg** [comment]
Sure, no problem. I'll just do another issues in the mean time. I'm not in a hurry for this endpoint :)

**Comment by ekapassa** [comment]
@anapolg API endpoint for getting specific License record created!    

**Endpoint:**    
`curl -v -H "Content-type:application/json" http://pre-int-sp-ath.5gtango.eu:32002/api/v3/slas/licenses/{nsi_uuid}`    
**Response:** 
```json 
{"current_instances":"test","allowed_instances":"20","license_type":"public","ns_uuid":"a9ecf352-136b-475f-842e-1d780fa7bb52","nsi_uuid":"test2","cust_username":"sonata@support.com","sla_uuid":"e80a9a9b-164b-446c-9fca-bd1e67a53224","license_status":"test","license_expiration_date":"2020-12-01T00:00:00Z"}```
