### ISSUE TITLE
[SP settings endpoints] List the endpoints in a new page

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-portal#312]
Request VIMs and filter per type = 'endpoint' to get the list

**Comment by anapolg** [comment]
Hi @carlos-f-parada how this should be displayed in the Portal? A new page under [VIMs menu] (https://pre-int-sp-ath.5gtango.eu/settings/vim) displaying the endpoints and their most important attributes (name, type...)?

**Comment by juanlucruz** [comment]
The only useful fields that contain an **endpoint** row is just the type and name, and something that is not mandatory (imho) but also important could be the city and country.

**Comment by carlos-f-parada** [comment]
@anapolg it should be a menu at the same level as VIMs and WIMs. In this case (at leas by now) they can just be listed and see details, not other CRUD operations. The parameters to list should be the same as for the others (e.g. use - if empty). As @juanlucruz says, the information from endpoints is quite less.
Did I respond to your questions?
