### ISSUE TITLE
[SM License] Buy a license

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-portal#321]
API reference https://github.com/sonata-nfv/tng-sla-mgmt/wiki/API-Specification-master#licensing

Buy the license when the user selects the buy button

**Comment by anapolg** [comment]
@ekapassa the body to create a license is composed by:
```
		const license = {
			ns_uuid,
			sla_uuid,
			license_type,
			license_exp_date,
			license_period,
			allowed_instances
		};
```

Therefore my proposal for the buying process is to have a pop up with:
- A select to choose the SLA
- A select to choose the NS
- Is it really required to have a select with license type equals something else than private?? If you buy a license it has to be private right?
- A calendar field to include the expiration date
- How should I consider the period? A select with predefined options? Another calendar field?
- An input field to include a number from 1 to ?

**Comment by ekapassa** [comment]
Well.. the only input parameters that you need to send in the sla_uuid and the ns_uuid. 
The api is like this --> `curl -X POST -H "Content-type:application/x-www-form-urlencoded" -d "ns_uuid=<>&sla_uuid=<> http://localhost:8080/tng-sla-mgmt/api/slas/v1/licenses/buy`  including the auth TOKEN toward the gatekeeper

**Comment by ekapassa** [comment]
I have documented it wrong here--> https://github.com/sonata-nfv/tng-sla-mgmt/wiki/API-Specification-master     
Sorry...:/  will update the wiki as well
