### ISSUE TITLE
[V&V Test Recommendations] Display test recommendations to the user

### ISSUE THREAD

**Issue by mtouloup** [sonata-nfv/tng-portal#322]
Regarding the tests recommendations to the user....

1) The user enters the portal
2) He navigates to the NS section with the tests. 
3) At that point, portal requests recommendations from tng-vnv-dsm based on the logged in user
4) Recommendations arrives to the portal and displays them
5) The users chooses one or many (optional)

Here you can find a working swagger documentation of the tng-vnv-dsm end points:
http://pre-int-vnv-bcn.5gtango.eu:4010/api/v1/

Feel free to ping me for anything more you need.

**Comment by anapolg** [comment]
What are exactly those recommendations? And why do you want them in the NS list of the V&V?

**Comment by anapolg** [comment]
Won't do
