### ISSUE TITLE
[SM license] License inactive deactivate the detailed view

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-portal#333]
"We only have an active license if we have an instance (otherwise the status of the license is inactive ==> no details for this license (i.e. cutomer etc)"

Therefore we have two options to consider in this case:

A) the inactive licenses displayed in the list of licenses (if any) should not be opened => Deactivate the detailed view of the licenses with status inactive.
B) Filter the licenses with status inactive not to display them in the list of licenses.

Please @ekapassa tell me which one you prefer.

**Comment by ekapassa** [comment]
Hello @anapolg. Sorry for the delay, I was fixing some bug in the status of the licenses. Let's go with option (B)
