### ISSUE TITLE
[SP SLA template creation] Send NS name in the guarantees list API

### ISSUE THREAD

**Issue by ekapassa** [sonata-nfv/tng-portal#338]
Include in the get guarantees list api, the selected ns name.    

Like this -->`../configurations/guaranteesList/{the ns name the user has selected in the previous dropdown menu>}`     

When this is implemented, please let me know before merging the related PR.    

cc: @anapolg , @mtouloup

**Comment by anapolg** [comment]
Hi @ekapassa the name or the uuid?

**Comment by ekapassa** [comment]
The name pleaseOn Jun 10, 2019 10:24, anapolg <notifications@github.com> wrote:Hi @ekapassa the name or the uuid?

**Comment by anapolg** [comment]
Done. Can you activate this in the SLA manager to test? Right now I'm getting:
Request URL: http://pre-int-sp-ath.5gtango.eu:32002/api/v3/slas/configurations/guaranteesList/communication-pilot
Request Method: GET
Status Code: 404 Not Found

**Comment by ekapassa** [comment]
@anapolg Activated! Can you test it again and let me know?

**Comment by anapolg** [comment]
Done and tested from my side. It's been deployed in pre-int so you can check it (and the things from Friday). 
Please tell me if you find everything ok or if there is something else to change.
