### ISSUE TITLE
[SM slice instance] Remove 5qi and include SNSSAI id

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-portal#340]
Remove 5qi field from slice instances (and templates if also included). Include the new field SNSSAI_identifier in NST:

  "SNSSAI_identifier": {
    "slice-service-type": "eMBB"
  },

There are three types of slices:
- enhanced Mobile Broadband slice (eMBB)
- Ultra Reliable Low Latency Communications slice (URLLC)
- massive Machine Type Communications slice (mMTC)

Show the type of slice in the slice template.

cc @alemanyp

**Comment by anapolg** [comment]
Done. Pending you test the following:
- Removed any reference to 5qi value
- Included field "SNSSAI_identifier" in NST (both in Service Platform and Service Management menus)

Also, are these fields required yet? I have them included in the information displayed but I do not see any of them arriving in the response.
- onboardingState
- operationalState
- notificationTypes
- userDefinedData

**Comment by alemanyp** [comment]
Thanks to solve the first point.

about the last 4 parameters, you are right, they do not exist anymore.

**Comment by anapolg** [comment]
Ok I've removed them. Closing the issue.
