### ISSUE TITLE
[SM Network Services] Display SLA associated to a NS

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-portal#345]
API for getting SLAs associated to a specific service implemented:
`curl -v -H "Content-type:application/json" http://pre-int-sp-ath.5gtango.eu:32002/api/v3/slas/templates/services/134daeab-0d7a-4096-8d6e-f1adc7705b02`

Response:
```
{
  "slas": [
    {
      "allowed_instances": 2,
      "vendor": "tango-sla-mgmt",
      "license_type": "trial",
      "license_exp_date": "2019-06-30T00:00:00Z",
      "name": "GOLD2",
      "d_flavor": "",
      "uuid": "bad36cf8-dcc6-410a-81c2-9156a7eb8f96",
      "version": "0.1"
    }
  ]
}
```

cc @ekapassa @jbonnet

**Comment by anapolg** [comment]
Hi @ekapassa 
the idea is to show all the possible SLAs available to a NS descriptor? 
Where? In the SP menu or in the SM one?

**Comment by ekapassa** [comment]
Hello @anapolg 
If i remember correctly (because this issue is 5 months old)..the idea was to show this list of slas,, not in the SP menu...but inside its network service page.

**Comment by anapolg** [comment]
So the idea is to show a list of SLAs related with the network service in here https://pre-int-sp-ath.5gtango.eu/service-management/network-services/services/683d6e7a-a2bc-43fa-9c38-35fd8b0b4e4b just below the list of VNFs for example?

Is there any use for the list? Any action? Or just displaying them?

**Comment by ekapassa** [comment]
Yes that's right!
To the best of my knowledge no, there is not any use for the list - just displaying them.

**Comment by anapolg** [comment]
Ok, working on it.

**Comment by anapolg** [comment]
We have a problem with the error codes:
You are responding with a 404 Not found error when there are no SLAs for a particular network service (an empty array). This is an error to be shown only when the resource or page you are trying to open could not be found on the server side.

![image](https://user-images.githubusercontent.com/35800470/69787317-8fa99180-11bc-11ea-83a7-9332efeb86b1.png)

![image](https://user-images.githubusercontent.com/35800470/69787337-9b955380-11bc-11ea-8570-6edf5b8e8f26.png)

In this case, it was found. It simply has no items inside, This should be a 200 OK as a response. In any other case different than 2XX codes, the HTTP module of the app will recognize the code as an error, which is the normal.

**Comment by anapolg** [comment]
Ready from Portal side. Still, it would be good to change in server side what I commented below to avoid displaying errors that are not errors.

**Comment by ekapassa** [comment]
@anapolg Thank you!
I will fix this issue asap

**Comment by ekapassa** [comment]
@anapolg Is this integrated already or not? Because I cannot see the SLA associated with the ns uuid = 095539af-6688-42e7-8c1f-9563f27cb6f2 (in pre-int)

https://pre-int-sp-ath.5gtango.eu/service-platform/network-services/095539af-6688-42e7-8c1f-9563f27cb6f2

**Comment by anapolg** [comment]
Yes, it is integrated but SLAs are only shown in SM menu. In here: https://pre-int-sp-ath.5gtango.eu/service-management/network-services/services/095539af-6688-42e7-8c1f-9563f27cb6f2 

From this `..the idea was to show this list of slas,, not in the SP menu...but inside its network service page.` I understood that the SP menu is not a target for this.

**Comment by ekapassa** [comment]
oh yes..you are right.my mistake! mixed the links
