### ISSUE TITLE
[Settings VIM] Include two more fields

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-portal#346]
Two more fields for VIM creation/edition:
- "external_router_ip"
- "management_flow_ip"

Example here:
https://git.cs.upb.de/5gtango/generalInfo/wikis/devel-ia-vim-wim-configs#api

* Add “ID” in the end of “External network” and “External router” to be differentiated from the new ones.

cc @carlos-f-parada @juanlucruz

**Comment by juanlucruz** [comment]
A new field is needed:
`floating_ip_ranging: xxx.xxx.xxx.xxx-xxx.xxx.xxx.xxx`
for the management flow to allowing access to VNF management interface
