### ISSUE TITLE
[Dashboard] Disk usage VM information only use the first disk on the list

### ISSUE THREAD

**Issue by felipevicens** [sonata-nfv/tng-portal#347]
The disk information usage of the VM only shows the first disk. Sometimes the first partition is loop0 that is 100% usage while the real partition where is installed ab being used by the SP is located in other partition.

I would like to change this graph and instead to select the first dist on the array, show a line graph that includes all disks information to be more precise.

**Comment by anapolg** [comment]
Hi @pkarkazis is it possible to generate a graph where all disks information is displayed with the different levels of disk consumed in each of them? Maybe something like the case of CPU data:

![asdf](https://user-images.githubusercontent.com/35800470/59188095-28991180-8b77-11e9-9579-30025dc30b38.png)

The problem that Felipe has is that the graph with the percentage is showing information about the first disk only (in the picture the first disks have 100% but the last one still 11%). He wants to see the data of all of them together.

![image](https://user-images.githubusercontent.com/35800470/59187986-f2f42880-8b76-11e9-92fc-8bc351565a03.png)

**Comment by anapolg** [comment]
Can we close this @felipevicens ?
