### ISSUE TITLE
[SP Authentication] Send auth token in instantiation request

### ISSUE THREAD

**Issue by ekapassa** [sonata-nfv/tng-portal#369]
Probably there is a problem sending the authentication token towards the GK during the instantiation request.     

Through the portal there is a problem extracting the user information from that token, but using the API + the authentication token, everything is working in the GK side    

cc: @anapolg @jbonnet

**Comment by ekapassa** [comment]
The issue still remains.....

@jbonnet I think e need you here as the GK expert.....    
THE ISSUE: The portal send the AUTH TOKEN during the instantiation request (as depicted in the first figure), but the GK does not process is correctly in order to add the user information in the response (as depicted in the second figure)     

The weird thing here is that when we are trying the instantiation process through the API (curl) the flow is as expected......

![image](https://user-images.githubusercontent.com/15989176/61622430-6e202280-ac7d-11e9-9260-a56f1c9c3ac0.png)


![image](https://user-images.githubusercontent.com/15989176/61622440-74160380-ac7d-11e9-807d-e46b1ba541db.png)

**Comment by jbonnet** [comment]
@felipevicens Should there be any filter of the Authorization hedaer in the API GTW?

**Comment by ekapassa** [comment]
Closing this issue...
Currently working (5 instantiations without a problem) I will keep an eye on this though
