### ISSUE TITLE
Local instance of VNV 

### ISSUE THREAD

**Issue by sinaure** [sonata-nfv/tng-portal#373]
[
![Capture](https://user-images.githubusercontent.com/16242967/61781094-06481400-ae04-11e9-8dc6-460687fea5b0.PNG)
](url)

error in the settings/endpoint page:

api/v3/settings/vim return error 400

![Capture1](https://user-images.githubusercontent.com/16242967/61781253-53c48100-ae04-11e9-88fc-6d93d9e4bfa5.PNG)

error in /service-platform/packages

/api/v3/services  return 504 gateway timeout

**Comment by felipevicens** [comment]
@sinaure can you paste here the output of 
docker ps -a
?

**Comment by sinaure** [comment]
[out.txt](https://github.com/sonata-nfv/tng-portal/files/3426024/out.txt)

**Comment by anapolg** [comment]
`/api/v3/services` return 504 gateway timeout is not a portal problem. It is a timeout due to connection issues. Regarding the other I am going to check.

**Comment by anapolg** [comment]
Regarding the other problem (api/v3/settings/vim return error 400):
![image](https://user-images.githubusercontent.com/35800470/61783526-3db8bf80-ae08-11e9-89ed-95aa7bf7c0e6.png)

It seems it is fine in pre-int environment. Can you try CTRL+SHIFT+R in Portal and go again to that page? In case it does not work, when did you installed this portal? In which environment? Can I access it?

**Comment by felipevicens** [comment]
Planner is restarting. 
```bash
59f9f8b7f5fd        sonatanfv/tng-vnv-planner:dev            "java -jar -Dspring.…"   25 hours ago        Restarting (1) 28 seconds ago   
```
I've uploaded a patch for it to tng-devops. the issue is that the db planner is not created in the db. You can run this command in your host:
```bash
docker exec -t son-postgres psql -h localhost -U sonatatest -d gatekeeper -c "CREATE DATABASE planner"
```

For DSM, can you paste here the logs?
```
docker logs 1c08e5316e9d
```

**Comment by mtouloup** [comment]
For the DSM, there was a problem with a json-logging library... I've dixed it today with a PR so the latest version should be okay...

**Comment by felipevicens** [comment]
@sinaure to have the right platform installed, please use the variable -e platform=vnv in the deployment command or change the file host_vars/localhost the variable platform: vnv

**Comment by felipevicens** [comment]
@mtouloup I'll promote the version to dev

**Comment by felipevicens** [comment]
So @sinaure to fix both issue run the following commands:
```
ansible-playbook roles/vnv.yml -i environments -e target=localhost --ask-vault-pass -e component=tng-vnv-dsm
```
```
ansible-playbook roles/vnv.yml -i environments -e target=localhost --ask-vault-pass -e component=portal -e platform=vnv
```
As you know the password is `sonata`

**Comment by sinaure** [comment]
this works 

sudo ansible-playbook roles/vnv.yml -i environments -e "target=localhost" -e platform=vnv  --ask-vault-pas s
--
