### ISSUE TITLE
test plans and packages list page not working on VnV

### ISSUE THREAD

**Issue by sinaure** [sonata-nfv/tng-portal#375]
after having configured the SP 
http://192.168.1.181/api/v3/tests/plans  is error 404

![Capture](https://user-images.githubusercontent.com/16242967/61793682-f0484c80-ae1f-11e9-8904-e3b726d5e4ff.PNG)

**Comment by sinaure** [comment]
during the execution of ansible script I checked the errors and even if at the end the final comment show no errors:


localhost                  : ok=59   changed=29   unreachable=0    failed=0


 I have a fail here:

TASK [vnv : create planner's database for sonatatest] ******************************************************************************************************* fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/bin/docker exec -ti son-postgres psql -h localhost -U sonatatest -d gatekeeper -c 'CREATE DATAB ASE planner;'", "delta": "0:00:00.080297", "end": "2019-07-24 14:11:10.830573", "msg": "non-zero return code", "rc": 1, "start": "2019-07-24 14:11:10.750276" , "stderr": "the input device is not a TTY", "stderr_lines": ["the input device is not a TTY"], "stdout": "", "stdout_lines": []}                             ...ignoring
--

**Comment by felipevicens** [comment]
ok maybe I've to remove the t from the command. I'll upload a patch

**Comment by anapolg** [comment]
I am sorry to announce that this is not a Portal issue: 

- The timeout is an error received because there is nothing answering on the server side.
- The 404 no route found has the right route so maybe the problems you are seeing in the deployment affect the results you are obtaining in the Portal.

Please do not open issues not related to Portal in here :)

**Comment by felipevicens** [comment]
Actually Ana, 404 is the expected result right? if no plans in the backend

**Comment by anapolg** [comment]
404 is route not found if I remember correctly. If no plans it was a 200 [ ]

**Comment by felipevicens** [comment]
Installation fixed in https://github.com/sonata-nfv/tng-devops/pull/236

**Comment by anapolg** [comment]
@felipevicens I've checked the API from V&V and the expected result when OK is a code 200. So 404 is probably due to a failure in the communication from Portal to the service.

**Comment by sinaure** [comment]
"Gateway Time-out", url: "http://192.168.1.181/api/v3/services"

All the endpoint are in timeout

**Comment by anapolg** [comment]
The timeout is an error received because there is nothing answering on the server side.

**Comment by sinaure** [comment]
ok is server side issue thx Ana I'll reopen it on Planner side
