### ISSUE TITLE
[SDK] On-board to service platform directly

### ISSUE THREAD

**Issue by stefanbschneider** [sonata-nfv/tng-portal#380]
Once packaging works, add a text field to specify the URL of a service platform and a button to click and onboard the package directly.

In the background simply execute the corresponding REST call.

Current developments in `sdk-dev` branch of my fork.

**Comment by stefanbschneider** [comment]
Got an error when trying to upload generated projects.

```bash
$tng-cli package -u eu.5gtango.5gtango-project-sample.0.1.tgo
tng-cat-be: could not upload NS descriptor: (400) {"error":"Platform not aligned with format of descriptor"}
False
```

Error disappears when deleting the OSM descriptors (and removing them from the `project.yml`).

**Comment by stefanbschneider** [comment]
Next step is integration into SDK portal. Two options:

* Directly via REST call from portal
* Install tng-cli in SDK backend image, add an endpoint to tng-sdk-project to use it for onboarding

I'll try in this order

**Comment by stefanbschneider** [comment]
This is how the tng-cli onboards packages: https://github.com/sonata-nfv/tng-cli/blob/master/src/tnglib/packages.py#L166

**Comment by stefanbschneider** [comment]
Not sure how to send remote files (from the project endpoint). See https://stackoverflow.com/q/57628638/2745116

**Comment by stefanbschneider** [comment]
Should work now, but when I try to make the post request from the locally deployed portal, I get a CORS error. Even if I disable CORS in Chrome:

![Anmerkung 2019-08-23 171236](https://user-images.githubusercontent.com/28340802/63603233-7d222980-c5c9-11e9-9e67-b9c7922f2cfe.png)

@anapolg Do you have experience with how to deal with CORS issues when interacting with the SP (pre-int in this case)?

**Comment by anapolg** [comment]
Hi, for CORS I open the browser with disabled web security:
`google-chrome --disable-web-security --user-data-dir=/tmp/chrome`

**Comment by stefanbschneider** [comment]
Ok thanks. I tried to disable CORS inside chrome with an addon so far, but I'll try with your command next time. Also related (reminder for myself): https://stackoverflow.com/a/24290256/2745116
