### ISSUE TITLE
[SDK] Improve look and feel

### ISSUE THREAD

**Issue by stefanbschneider** [sonata-nfv/tng-portal#424]
Currently, the SDK portal looks very different from the rest of the portal. I should make it more consistent such that we can finally merge it in the end.

**Comment by stefanbschneider** [comment]
Improved descriptor gen page. Next is the descriptor detail/display page. Maybe I can make it look a bit like the service detail page of the SP portal

**Comment by stefanbschneider** [comment]
Currently, the main page, once the descriptors and project are generated, looks like this:

![image](https://user-images.githubusercontent.com/28340802/65127936-c878fd80-d9f8-11e9-9493-7bfab54b3c05.png)

I'll try to make it look more like the rest of the portal.

**Comment by anapolg** [comment]
You have the mockups in here https://invis.io/HRMUQZJUXZY#/354627799_2-1-2_Package_Description_Focus_-name

You can navigate through them as if they were a real app clicking in the different buttons and so.

**Comment by stefanbschneider** [comment]
Nice thanks, these look great! For now, I'll go with something simpler that somehow matches the look of the rest of the portal, so we can integrate it there and use it for the review. I'd really focus on what we need for the review here and try to avoid extra effort.
