### ISSUE TITLE
[SDK] Integrate into main portal on `master`?

### ISSUE THREAD

**Issue by stefanbschneider** [sonata-nfv/tng-portal#431]
* [x] Check/ensure that SDK part works with code on `master`, eg, with authentication
* [ ] Discuss with Ana, José, Felipe if/how SDK portal should be merged to `master`
* [ ] Fix failing Jenkins CI on `master`: https://jenkins.sonata-nfv.eu/job/tng-portal/job/master/

**Comment by stefanbschneider** [comment]
@jbonnet @felipevicens @anapolg So far we kept the SDK portal in a separate `sdk` branch because there were still some bug fixes and adjustments I had to make.

Now the SDK portal is ready in its basic form and from my side, it's ready to be merged into `master`. In the end, the main use case is the final review, so we can but don't have to merge it to `master`. It could also stay separate.

What do you think?

**Comment by jbonnet** [comment]
@stefanbschneider I'm in favor of 'the least number of branches the better'. But we need to look into this in a case-by-case manner...

@anapolg @felipevicens what do you think? Are you confident enough? Shall we go for a merge now, or wait 'till after Athens' F2F?

**Comment by anapolg** [comment]
I haven't been working on SDK Portal nor payed close attention to the developments made. I can't really have an opinion in this matter since I haven't even opened it. 
It is @stefanbschneider who knows the better about the SDK Portal status and its integration with master. I would say this decision depends on him (check that everything works) and on what you want for the Portal in a future (unify it or leave it as an independent feature).

**Comment by stefanbschneider** [comment]
Regarding the integration into `master`, I don't see an issue. I have the latest code from `master` in the `sdk` branch, so it should be a clean extension from what we currently have in `master`.

The result would simply be an additional menu button with the SDK functionality. It wouldn't affect any of the existing portal features. I tried to make the SDK portal look and feel quite similar to the rest of the portal, but there is surely potential for improvement. Nevertheless, my plan would be to keep the SDK tailored to the needs of the final review, since I have to concentrate effort on the SM pilot.

I also have no opinion on whether to merge it or not. For me it's also ok if it stays separate. I don't see any big advantages or disadvantages either way. Just wanted to know what you think.
