### ISSUE TITLE
[SM slice instantiation request] Update the request with the new request model

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-portal#437]
Coming from https://github.com/sonata-nfv/tng-gtk-sp/issues/359

```
{
  "nstdId": "",
  "request_type": "CREATE_SLICE",
  "name": "",
  "description": "",
  "callback": "",
  "instantiation_params": [
    {
      "subnet_id": "", ---> Maintain from nstd.slice_ns_subnets list. (key to use is "id")
      "sla_id": "",
      "sla_name": "",
      "ingresses": "", (offer the possibility to include them like ns instantiation. optional)
      "egresses": "", (offer the possibility to include them like ns instantiation. optional)
      "vim_id": "uuid" (offer a select to the user in order to choose one vim. optional)
    }
  ]
}
```

**Comment by anapolg** [comment]
Also include a field with the format key:value named instantiation parameters per NS.

cc @felipevicens

**Comment by alemanyp** [comment]
Regarding previous comment... @anapolg 

{
  "nstdId": "",
  "request_type": "CREATE_SLICE",
  "name": "",
  "description": "",
  "callback": "",
  "instantiation_params": [
    {
      "subnet_id": "", ---> you take each id from the nstd.slice_ns_subnets list. (key to use is "id")
      "sla_id": "",
      "sla_name": "",
      "ingresses": "",
      "egresses": "",
      "vim_id": "uuid",
      **"params": {key: value, key2:value, key3:value}**
    }
  ]
}
