### ISSUE TITLE
[SP runtime policies] Rename policy actions offered

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-portal#438]
```
		"actions": [{
			"action_object": "ElasticityAction",
			"action_type": "ScalingType",
			"name": "addvnf",
			"value": "1",
			"target": {
				"name": "wac-vnf",
				"vendor": "quobis",
				"version": "0.6"
			}
		}]
          	"actions": [{
			"action_object": "AlertAction",
			"action_type": "LogMessage",
			"name": "intrusion",
			"value": "1",
			"target": {
				"name": "lhc-vnf2",
				"vendor": "eu.5gtango",
				"version": "0.8"
			}
		}]
```

**Comment by anapolg** [comment]
@efotopoulou only this two actions? `addvnf` and `intrusion`? Or there was an API to GET them? Sorry, I do not remember this details.

**Comment by efotopoulou** [comment]
the rename of the actions refers only to the intrusion . the ElasticityAction works fine.

Right now when creating an intrusion action from the portal, it is saved like this at the catalogues.
Here is an example i created at the portal https://int-sp-ath.5gtango.eu/service-platform/policies/runtime-policies/d3b1d335-d119-42ca-8f9c-2e42be82397f
```
                "actions": [
                    {
                        "name": "alertmessage",
                        "value": "1",
                        "action_object": "SecurityAction",
                        "target": {
                            "vendor": "eu.5gtango",
                            "name": "squid-vnf",
                            "version": "0.2"
                        }
                    }
                ]

```

but it should be like this
```
		"actions": [{
			"action_object": "AlertAction",
			"action_type": "LogMessage",
			"name": "intrusion",
			"value": "1",
			"target": {
				"name": "lhc-vnf2",
				"vendor": "eu.5gtango",
				"version": "0.8"
			}
		}]
```

**Comment by anapolg** [comment]
Ok. let's see:
- `action_object` comes from the list of actions offered, this one below:
![image](https://user-images.githubusercontent.com/35800470/70050140-924a2380-15ce-11ea-90a0-bd9c72cf7ecb.png)
Here there is no Alert action so I guess the list should be expanded. Can you list me the options I should include in this list?

- `"action_type": "LogMessage",` this param is new for Portal. Should it be another dropdown?

- `"name": "intrusion",` the names offered right now are `add vnf` and `remove vnf`. Nothing else. Should I include more options to that dropdown?

**Comment by efotopoulou** [comment]
1. you should not add any dropdown about the action_type. This is filled automatically by the policy manager
2. "addvnf" and "removevnf" dropdown options should be offered to the end user only when the selected "action_object" is the "ElasticityAction". if the "action_object" is "AlertAction" the only option (at least for the last release of sonata) is the "intrusion" option.

**Comment by anapolg** [comment]
But the only actions (action_object) offered to the user are `ElasticityAction` and `SecurityAction`. Then, this issue was originated to add a third action_object called `AlertAction`, is that right?

And this action_object (`AlertAction`) has the related action name `intrusion`. Right?

![image](https://user-images.githubusercontent.com/35800470/70147079-da874580-16a3-11ea-83f6-787326ff2f65.png)

![image](https://user-images.githubusercontent.com/35800470/70146780-330a1300-16a3-11ea-9abd-55fcdf75b97b.png)

**Comment by efotopoulou** [comment]
Sorry for confusing you. There is NO SecurityAction any more. 

The supported actions are only two:
A.  ElasticityAction (action_object) with two sub-options A1. addvnf (name) & A2. removevnf (name)
B. AlertAction (action_object) with one sub-option B1. intrusion (name)
