### ISSUE TITLE
[V&V analytics engine] New page to create an analysis in analytic engine

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-portal#445]
Related to https://git.cs.upb.de/5gtango/UserStories/issues/559

1. Create a "Create New Analytic Process" button in the list page that routes to the creation page.
2. Add a form with:
    - Name of the process as the title
    - Tests dropdown: list of tests
    - Analytic service dropdown: list of the available services @efotopoulou ?
    - Monitoring metrics dropdown: list of monitoring metrics coming from `policies/monitoring_metrics` @efotopoulou ?
3. Add RUN and CANCEL buttons on the upper right corner.

![image](https://user-images.githubusercontent.com/35800470/66927937-f0c43e00-f030-11e9-9fa3-cb2ac83baf04.png)

Is [this](https://github.com/sonata-nfv/tng-analytics-engine/wiki/Execute-Analytic-Service-for-specific-test) the request to be made @efotopoulou ?

**Comment by efotopoulou** [comment]
Hi @anapolg!

about the point 2 i pass you some useful information:

- Name of the process as the title : this should be just a String
-Test Results dropdown: list of test results (http://pre-int-vnv-bcn.5gtango.eu:32002/api/v3/tests/results)
-Analytic service dropdown: list of the available services (http://pre-int-vnv-bcn.5gtango.eu:8085/list)
-Monitoring metrics dropdown: list of monitoring metrics coming from tng-analytics-engine (http://pre-int-vnv-bcn.5gtango.eu:8085/tests/vnv/{nsr_id}/metrics)

:-)

**Comment by anapolg** [comment]
And how do I get the `nsr_id` to get the monitoring metrics?

**Comment by efotopoulou** [comment]
From the test results REST API : http://int-vnv.5gtango.eu:4012/trr/test-suite-results
per test result you can fetch the nsr_id. The nsr_id is the field with name `instance_uuid`
```
{
	"created_at": "2019-10-17T09:44:05.877+00:00",
	"ended_at": "2019-10-17T09:44:05.852Z",
	"instance_uuid": "603e4785-9046-4d9c-93b5-0655019ba45d",
	"package_id": "7b3e63b2-8b68-402d-a44a-73b9d30c4d12",
	"service_uuid": "132fbd52-6a64-4689-88fc-63d3eb8444dc",
	"started_at": "2019-10-17T09:42:16.781Z",
	"status": "PASSED",
	"test_uuid": "b1de20f9-29c8-415d-a005-5899d715dc63",
	"updated_at": "2019-10-17T09:44:05.838+00:00",
	"uuid": "9c0b7943-a671-4ee1-b8a4-bf2b7ad1658f"
}
```

**Comment by anapolg** [comment]
Ready in PR https://github.com/sonata-nfv/tng-portal/pull/447 waiting to be checked by @efotopoulou

**Comment by efotopoulou** [comment]
"metrics" field is an optional field. When no metrics are selected from the UI, "metrics" field should be skipped off.
