### ISSUE TITLE
[Bug] Network service instance error displaying function instances

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-portal#453]
https://int-sp-ath.5gtango.eu/service-management/network-services/network-service-instances/281b49c5-63f9-48c6-94de-ddc2ccd7b73c

```
VM150:1 GET https://int-sp-ath.5gtango.eu/api/v3/records/functions/31a7b74a-eda8-41a0-9be9-6b4f8d93b226 404 (Not Found)

e {headers: n, status: 404, statusText: "Not Found", url: "https://int-sp-ath.5gtango.eu/api/v3/records/functions/31a7b74a-eda8-41a0-9be9-6b4f8d93b226", ok: false, …}

ERROR Error: Provided data source did not match an array, Observable, or DataSource
    at e.n._observeRenderChanges (main.46173dbaa1cce38cd1e0.js:1)
    at e.n.ngAfterContentChecked (main.46173dbaa1cce38cd1e0.js:1)
    at $r (main.46173dbaa1cce38cd1e0.js:1)
    at Kr (main.46173dbaa1cce38cd1e0.js:1)
    at Yr (main.46173dbaa1cce38cd1e0.js:1)
    at bi (main.46173dbaa1cce38cd1e0.js:1)
    at Fi (main.46173dbaa1cce38cd1e0.js:1)
    at Di (main.46173dbaa1cce38cd1e0.js:1)
    at bi (main.46173dbaa1cce38cd1e0.js:1)
    at Fi (main.46173dbaa1cce38cd1e0.js:1)
```

![image](https://user-images.githubusercontent.com/35800470/68593583-13ae0a80-0496-11ea-8d15-9bd1de550856.png)

cc @felipevicens

**Comment by felipevicens** [comment]
What is the issue? the message is clear, 404 not found and message error included. Do you expect something different?

**Comment by anapolg** [comment]
1. I expect that if 3 of the 4 VDU/CDU are received, they must be shown. If the forth fails, a message must be displayed to the user.
2. There is also an error with the datasource used to display the CDU/VDU which must be studied in case something is missing while parsing the received data (or when there is missing data to parse).

**Comment by felipevicens** [comment]
Do you expect something different in the tng-rep backend? Looks like the MANO started deleting things and didn't finished, so some things are not well and tng-portal is not able to process the 404.

**Comment by anapolg** [comment]
I don't know what happens / should happen in tng-rep. 
The Portal should be able to handle this kind of situation and right now it seems it is not able. Therefore this issue.

**Comment by felipevicens** [comment]
Okey! gogogo

**Comment by anapolg** [comment]
Not able to duplicate this error. Which ns were you using in this case? Do you remember?

**Comment by felipevicens** [comment]
It seems fixed now. Closing the issue
