### ISSUE TITLE
Policy Rules at UI

### ISSUE THREAD

**Issue by efotopoulou** [sonata-nfv/tng-portal#455]
Regarding Policy Rules UI , right now they include 3 columns, 

- name
- value
- inertia

but the end user does not understand which vnf this action will be applied , neither the monitoring rule(s) that participate to each Police Rule.
For that reason, it should be useful to see also this information per Policy Rule.

![image](https://user-images.githubusercontent.com/1914256/68952178-1a0af200-07c8-11ea-8823-4bcd1db28faa.png)

**Comment by anapolg** [comment]
There can be several VNFs affected by the action if different actions are defined for the same policy rule. The same happens with the monitoring rules. There can be more than one and the Portal would have to show in the table a concatenation of 
![image](https://user-images.githubusercontent.com/35800470/70056855-6e8dda00-15dc-11ea-921c-14c9b17c39b1.png)

The only option I see here would be to include more information when the table entry is clicked like in https://int-sp-ath.5gtango.eu/service-management/network-services/network-service-instances/273c656d-d564-4870-9ef3-5143179dce48 where you can click in an instance and see its relevant information.

**Comment by efotopoulou** [comment]
clicking on the action and seeing more information would be great!
Thanks a lot Ana!

**Comment by anapolg** [comment]
Do you want this just in the detailed view of the policy or also in the creation one  @efotopoulou ? Right now it is implemented in the detailed view. If I have to do the same in the creation one please tell me as soon as possible.
