### ISSUE TITLE
Add delete option at analytics results list.

### ISSUE THREAD

**Issue by efotopoulou** [sonata-nfv/tng-portal#456]
Add delete option at analytics results list.
The API to delete an analytic result is the following
DELETE REST CALL
http://int-vnv.5gtango.eu:32002/api/v3/analytics/results/{result_id}

**Comment by anapolg** [comment]
@jbonnet We need to add the verb delete to this endpoint for this to work:
https://github.com/sonata-nfv/tng-api-gtw/blob/master/tng-router/config/vnv_routes.yml#L167

I would add it myself but I am not sure to which roles I should give the verb delete. Admin, developer and customer? The three of them?

**Comment by jbonnet** [comment]
@anapolg Admin only?

**Comment by anapolg** [comment]
I would say developer too, or not? This is to remove analytic results from the list so I am not sure who should do this...

**Comment by jbonnet** [comment]
Ah, ok, yes, maybe dev as well...

**Comment by anapolg** [comment]
Should I add them or are you doing it?

**Comment by anapolg** [comment]
I am still receiving the method not allowed error:
Request URL: http://pre-int-vnv-bcn.5gtango.eu:32002/api/v3/analytics/results/5ddbe62107c0a80001aa4b5b
Request Method: DELETE
Status Code: 405 Method Not Allowed

any idea @jbonnet

**Comment by anapolg** [comment]
Ok, I think it is the transfer-encoding: chunked error again. Is it possible?

**Comment by anapolg** [comment]
Solved. Thanks @efotopoulou
