### ISSUE TITLE
Monitoring graphs  

### ISSUE THREAD

**Issue by pkarkazis** [sonata-nfv/tng-portal#457]
On VNF page after the "Show monitoring graphs" action, the generated query to Grafana requests chart from CNF dashboard not from VNF one.
"https://int-sp-ath.5gtango.eu/api/v3/monitoring/graphs/d-solo/CNF_dash/cnf?orgId=1&from=1573809324520&to=1573809326320&panelId=2&var-cnt_name=96c4d1ed-078c-4195-8cbb-850f5dab21b4&var-metric=cpu_util&theme=light&refresh=8s"

Also, the timestamps "from" and "to" should be UTC time.

**Comment by anapolg** [comment]
cc @felipevicens

**Comment by anapolg** [comment]
After adapting the requests of this graphs to VNFs/CNFs, I get this:

![image](https://user-images.githubusercontent.com/35800470/70044509-c881a600-15c2-11ea-912a-08417ada7d1a.png)

I am not sure why I get the whole Grafana panel. This did not happen before but it happens now. The problem I see is that if the user tries to change anything in the dropdown menus of the imported panel, the result is this one:

![image](https://user-images.githubusercontent.com/35800470/70044476-bacc2080-15c2-11ea-93e8-3fba8def884c.png)

The graph just won't work. Any idea @pkarkazis ? Do you see anything weird in Grafana for this to happen? The request I am doing for this graphs* does not include parameters such as `var-env` or `var-entity`. Could this be a reason for Grafana to send me the whole panel and not just the graph like in the Dashboard graphs**?

*Instance graph request: `http://int-sp-ath.5gtango.eu:32002/api/v3/monitoring/graphs/d/VNF_sp/vnf?orgId=1&from=1575370324762&to=1575370326562&panelId=2&var-id=7a420ac2-5ed0-4037-b2fc-65456db364b3&var-metric=haproxy_Uptime_sec&theme=light&refresh=8s`

**Dashboard graph request: `http://pre-int-vnv-bcn.5gtango.eu:32002/api/v3/monitoring/graphs/d-solo/sp_dash/sp?orgId=1&panelId=3&var-id=4fd837f6-5f49-11dc-a9ed-000ea629289b&var-entity=vm&var-env=pre-int-vnv-bcn.5gtango.eu:4fd837f6-5f49-11dc-a9ed-000ea629289b&theme=light&refresh=10s`

**Comment by pkarkazis** [comment]
@anapolg we haven't made any changes in Grafana last three months, also the graphs in sp dashboard are coming correctly (without any sidebar).

**Comment by anapolg** [comment]
I know. That's why I ask if there is any difference in the built graphs for the instances monitoring and the ones from the Dashboard in the Portal. They have different parameters in the request (`var-env` and `var-entity` for example). Why that difference? Does it mean something? Am I missing something in the request that I do not see?
