### ISSUE TITLE
Policies duplication should lead to a create policy view

### ISSUE THREAD

**Issue by efotopoulou** [sonata-nfv/tng-portal#458]
Policies duplication creates an equal policy with the name of "Copy-of-previous-name" that is not editable.
Instead of saving it directly it should load the policy at a create view so as to permit the user to modify any field.

**Comment by anapolg** [comment]
I guess that now I have to use the creation endpoint instead of the duplicate endpoint, right? I am saying this because the duplication one is a GET with the duplicated policy uuid. No possibility to send the modified data in there.

**Comment by efotopoulou** [comment]
exactly. you should use the creation endpoint :-)

**Comment by anapolg** [comment]
Pending to be checked by @efotopoulou 

Somehow, the format of the received data differs from the one sent by the Portal when creating the policy
`condition` attribute changes 
from 
(Portal sends) `condition: "wac-vnf:vdu01:cpu_util"`
to
(Policy manager sends portal) `condition: "sippoServerSessions"`

and the format of the name changes 
from 
(Portal sends) `wac-vnf:vdu01:memory_usage:<444`
to
(Policy  manager sends portal) `wac-vnf:vdu01:cpu_util:more222`

**Comment by anapolg** [comment]
Portal will do the changes over this data format. Name and condition parameters will be sent as defined above.
