### ISSUE TITLE
[Requests] Show deployment time of every request

### ISSUE THREAD

**Issue by alemanyp** [sonata-nfv/tng-portal#459]
Calculate deployment time for every request with updated_at - created_at

**Comment by anapolg** [comment]
This is how Portal shows the requests duration
![image](https://user-images.githubusercontent.com/35800470/69554894-c015e380-0fa2-11ea-88e8-97960a97d2ce.png)

I just parse the received seconds and remove the ms. So no calculation on the Portal side. This comes in the response of GET `http://pre-int-sp-ath.5gtango.eu:32002/api/v3/requests`

**Comment by jbonnet** [comment]
@anapolg That just measure the time the MANO took. To take the end-to-end time taken, you need to subtract from the `updated_at` field the `created_at` field: in the case shown, the request took about 21mins, and not seconds...

**Comment by anapolg** [comment]
This is for every request? Or should I display it in the instances view?

**Comment by jbonnet** [comment]
@anapolg Every request, be it service or slice instantiation or termination, migration, scaling...

**Comment by anapolg** [comment]
Then you can remove the field duration from requests response since I will be no longer using it.
