### ISSUE TITLE
Instantiation params don't work

### ISSUE THREAD

**Issue by stefanbschneider** [sonata-nfv/tng-portal#472]
It seems like passing instantiation params via the portal doesn't work.

I just tested it with NS2 of the industry pilot and passed parameter "MQTT_BROKER_HOST": "10.200.16.31", which should set the env var of the instance accordingly.

Still, when checking the instantiated VNF, the env var was not set correctly:

```
root@eu-5gtango-smpilot-mdc-0-1-658a7b60-b875c989f-rhlpt:/# env | grep MQTT
MQTT_BROKER_PORT=1883
MQTT_BROKER_HOST=172.31.13.158
```

It works fine when using `tng-cli` with the `--params_file` flag.

Belongs to #443

**Comment by anapolg** [comment]
Hi, some questions:
Which environment?
Which instantiation? NS or slices?

**Comment by stefanbschneider** [comment]
> 
> 
> Hi, some questions:
> Which environment?

https://int-sp-ath.5gtango.eu

> Which instantiation? NS or slices?

NS, eg, https://int-sp-ath.5gtango.eu/service-management/network-services/services/a5d565d6-aa5e-4204-b3d9-c3a8fcf9f853

**Comment by anapolg** [comment]
Hi, I've just merged what I think is the solution to your problem. Can you please try again whenever possible and confirm me if it works for you? (It should be deployed in both pre-int and int environments).

**Comment by stefanbschneider** [comment]
Hi, thanks! 

I just tested on int, and it still didn't work. The env var is still unchanged

```
# env | grep MQTT
MQTT_BROKER_PORT=1883
MQTT_BROKER_HOST=172.31.13.158
```

**Comment by anapolg** [comment]
Then I think we need someone else cause I saw the request sent and I am sending the params as:

![image](https://user-images.githubusercontent.com/35800470/69738394-56c6d980-1136-11ea-96cc-f47586bdd194.png)

![image](https://user-images.githubusercontent.com/35800470/69738328-3a2aa180-1136-11ea-9a7d-b815cced7777.png)

**Comment by stefanbschneider** [comment]
I just checked your service on k8s and it worked!

```
localadmin@k8s-master:~$ kubectl -it exec eu-5gtango-smpilot-mdc-0-1-f83d83d7-868dd8cf48-g4s9l bash
root@eu-5gtango-smpilot-mdc-0-1-f83d83d7-868dd8cf48-g4s9l:/# env | grep MQTT
MQTT_BROKER_PORT=1883
MQTT_BROKER_HOST=10.200.16.31
```

Not sure where I went wrong, but I guess this is solved now. I'll try again with the Portal next time and let you know if it doesn't work then.

**Comment by anapolg** [comment]
Mmmm I think I might know... you should try reloading your Portal tab with CTRL+SHIFT/MAYUS+R... Your Portal version might be yet the old one and it did not get updated. This happens sometimes...
