### ISSUE TITLE
[VnV standalone monitoring API ]

### ISSUE THREAD

**Issue by sinaure** [sonata-nfv/tng-portal#475]
as discussed here 
https://github.com/sonata-nfv/son-monitor/issues/138

**Comment by sinaure** [comment]
From an exchange with panos

Panos Karkazis @pkarkazis 7:54
Hello @sinaure,
I saw your issue in son-monitor (sonata-nfv/son-monitor#138) but I am not sure that I understood your point. Could you please provide me a more detailed description of the problem? For example, where the problem occurred, in which env did you notice it etc ?

aureliano sinatra @sinaure 09:35
Hi Panos, I've open this issue in duplicate with tng-api-gateway I am not sure is related with son monitor... Anyway this is the scenario:
I've installed the VnV on a VM in our 'EasyglobalMarket' dev environment (out of 5Gtango network)
we are of course in vpn
test plan execution stuck between tng-api-gateway and tng-vnv-planner
on the log stack I see
a reference to pre-int-vnv-bcn.5gtango.eu
my question is if I am using a local environment for the VnV and a remote SP (Aveiro in this case)
why do I have pre-int-vnv-bcn.5gtango.eu in the callback?
looks something hardcoded
I should have instead my internal IP

Panos Karkazis @pkarkazis 13:26
This query is originated from the portal asking a graph from monitoring (via tng-api-gtw), I suppose that the portal asks monitoring charts regarding the machine that hosts the vnv. I think that the most appropriate person to ask is @anapolg, probably you must use an env variable...

**Comment by anapolg** [comment]
Please don't duplicate issues. This is https://github.com/sonata-nfv/tng-portal/issues/466 as I said in https://github.com/sonata-nfv/son-monitor/issues/138
