### ISSUE TITLE
[SM] Instances monitoring graphs

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-portal#482]
Monitoring metrics displayed for each unit does not match the ones displayed in Grafana.

cc @felipevicens

**Comment by anapolg** [comment]
The problem @felipevicens is that I get the monitoring metrics depending on the unit you select. So I see no error for the moment. Could you please relaunch the instances giving this problem to check them, the information received and the Grafana?

**Comment by felipevicens** [comment]
It is fixed now
