### ISSUE TITLE
Checking when alert icon is needed (new NS version is available)

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-portal#53]
Coming from [#283](https://git.cs.upb.de/5gtango/UserStories/issues/283).
Network services can have a newer version than the one running at the moment. That should be displayed in the available NS view next to the play button as an alert button.

**Comment by jbonnet** [comment]
@anapolg, just a minor note:

1. a NS may have more than one version in the Catalogue at the same time;
1. whatever the version of the NS, there might be zero, one or more instances running at the same time;

**Comment by anapolg** [comment]
@jbonnet 1. ok but even if there are more than one version of the same NS in the Catalogue, displaying the alert icon only depends on the existence of a newer version (still searching that BSS API to check if newer versions exist).
2. ok but if the alert button is displayed that only means that there is a newer version of the NS than the one running in the already created instances, right?

**Comment by jbonnet** [comment]
1. Yes. Sorry, forgot to help on that search2. YesEm 23/03/2018 16:08, anapolg <notifications@github.com> escreveu:@jbonnet 1. ok but even if there are more than one version of the same NS in the Catalogue, displaying the alert icon only depends on the existence of a newer version (still searching that BSS API to check if newer versions exist).
2. ok but if the alert button is displayed that only means that there is a newer version of the NS than the one running in the already created instances, right?

**Comment by anapolg** [comment]
Won't do
