### ISSUE TITLE
User roles in register

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-portal#66]
Related to user story [#288](https://git.cs.upb.de/5gtango/UserStories/issues/288).
The roles offered to the user in the registration process should come from a service announcing the different possibilities.

**Comment by anapolg** [comment]
Is this still valid @jbonnet ?

**Comment by jbonnet** [comment]
It is! Check sonata-nfv/tng-api-gtw#145, me @luishens01 and @felipevicens are still working on it.
