### ISSUE TITLE
[SP Placement policy] Request to save placement policy chosen

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-portal#86]
Coming from [#261](https://git.cs.upb.de/5gtango/UserStories/issues/261)  [#332](https://git.cs.upb.de/5gtango/UserStories/issues/332).
Request to save the option chosen by the Portal user.

**Comment by anapolg** [comment]
Do we have an endpoint for this @tsoenen ?

**Comment by tsoenen** [comment]
Hi Ana, I think this resides in the policy manager.

**Comment by anapolg** [comment]
Ok, I thought policy manager managed only runtime policies. Sorry. Then, @efotopoulou , do we have the endpoint for this?

**Comment by anapolg** [comment]
REST API: http://pre-int-sp-ath.5gtango.eu:8081/swagger-ui.html#/rules-engine-controller/listPlacementPoliciesUsingGET

**Comment by anapolg** [comment]
Missing fetch of datacenters if the placement policy is "Prioritise".

**Comment by efotopoulou** [comment]
Hi Ana, you can fetch the whole placement policy metadata from the relevant API:
https://github.com/sonata-nfv/tng-policy-mngr/wiki/API-reference
`GET the Placement policy | GET | /api/v1/placement`

Do you need an extra API?

**Comment by anapolg** [comment]
Hi @efotopoulou the thing is that when I try to save (POST) a placement policy everything seems to be allowed but from the Portal I only know of three possible options: Load balanced, Prioritise and Fill first. Are there any other or can the user introduce whatever they want?

Then, when I try to save the policy "Prioritise", it is supposed to contain a list of ordered datacenters but I am not sure which key I must use for this. For example, I use { "policy": "the_policy" } but which is the key for this datacenter list?

Finally, when I GET the policy and the policy is "Prioritise" I should always get a list of datacenters ordered by priority.

**Comment by anapolg** [comment]
Related to https://github.com/sonata-nfv/tng-policy-mngr/issues/111
